# Generated by Django 4.1.7 on 2023-11-11 17:19

from django.db import migrations


class Migration(migrations.Migration):

    initial_defaults = [
        {
            "id": 1,
            "title": "MIS407 Homework IA05",
            "desc": "Complete MIS407 Homework IA05",
            "priority": "4",
            "done": True
        },
        {
            "id": 2,
            "title": "Update Resume",
            "desc": "Update resume after finishing this semester",
            "priority": "2",
            "done": False
        },
    ]

    def insert_defaults(apps, schema_editor):
        Task = apps.get_model('tasks', 'Task')
        for row in Migration.initial_defaults:
            task = Task(**row)
            task.save()

    def remove_defaults(apps, schema_editor):
        Task = apps.get_model('tasks', 'Task')
        for row in Migration.initial_defaults:
            task = Task(**row)
            task.delete()

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_defaults, remove_defaults)
    ]
