# Generated by Django 4.2.6 on 2023-11-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0002_auto_20200410_1729"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song", name="album", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="song",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="song", name="year", field=models.CharField(max_length=4),
        ),
    ]
